### PR TITLE
Suggested changes for pimatic 0.9 readiness

### PR DESCRIPTION
**Pull request by mwittig**
Some changes are required to run the plugin with pimatic0.9. The essential changes are 
- Plugin for pimatic 0.9 shall contain a valid license tags as part of the package descriptor
- Updated angualr dependencies to get rid of post-installation errors (bower package installation)
- Updated pimatic peerDepencency to run with pimatic 0.9

Please review the changes carefully. I haven't tested with pimatic0.8. So, I am not sure changes are backwards compatible. I have noticed a glitch: When a toast message is displayed (running in debug at the moment, so I see many toast messages) the vertical scrollbar is display for time the toast message is visible.

### CODE REVIEW

**Comment by dennisschroer** [comment]
Thank you, I will look into it

**Comment by dennisschroer** [comment]
https://github.com/denniss17/pimatic-angular-material-frontend/commit/a2c364753b782a3f82508259d781117a1f94e615

I will release a new version soon (its now being tested in Travis)

**Comment by mwittig** [comment]
Excellent work! Much appreciated. 
Just tested v0.3.0 which works fine for me with pimatic 0.9 (beta)

**Comment by dennisschroer** [comment]
@mwittig Thank you. Your input was also welcome 👍

**Pull request merged**
